"""Builds the enriched results sections (redesign brief §1-§20) from the
report dict your `/analyze/{file_id}` route already writes to disk and
`/results/{file_id}` already reads back.

This is intentionally NOT a rewrite of the pipeline. Everything here reads
fields your graph already produces (`profile`, `cleaned_profile`,
`quality_score`, `cleaning_plan`, `recommendations`, `report`, `charts`) and
reshapes them with the Phase 1/2 formatting helpers (app/services/
overview.py, insights.py, quality_presentation.py, ml_presentation.py,
executive_summary.py, cleaning_report.py, before_after.py).

FIXED (this revision), two real bugs from the previous version:

1. Profile semantics were backwards. `data["profile"]` is the ORIGINAL
   pre-cleaning profile -- confirmed from agents/graph.py: `profiler_node`
   sets it once and nothing ever overwrites it. `agents/graph.py` now also
   persists `data["cleaned_profile"]` (post-cleaning, previously computed
   and discarded inside `ml_recommendation_node`). This module now uses
   `profile` as the true "before" and `cleaned_profile` as the true
   "after" -- real before/after cleaning comparisons are now possible
   whenever `cleaned_profile` is present, instead of always being omitted.

2. Chart image URLs were broken. `data["charts"]` holds visualizer.py's
   chart metadata dicts, whose `path` field is an ABSOLUTE FILESYSTEM PATH
   (e.g. `/srv/app/outputs/charts/abc123_bar_Sex.png`), not a URL. The
   previous version of this file passed that raw path straight to the
   frontend as if it were already a `/charts/...` URL --
   `safeResolveAssetUrl()` on the frontend correctly rejected it (doesn't
   match the `/charts/` prefix allowlist), so chart titles rendered but the
   `<img>` never did. Fixed by routing every chart path through
   `file_service.chart_path_to_url` -- the same shared conversion
   `routes.py`'s legacy `_charts_to_urls` uses, so both response shapes are
   guaranteed to agree.

3. FIXED (this revision) -- Bug #1: Overview/banner used the wrong profile.
   This module previously built `ctx` (feeding Overview, the "Upload
   Successful" banner, and Dataset Insights) from `profile_after or
   profile_original` -- i.e. it preferred the CLEANED profile whenever one
   was available. That made the upload banner and Dataset Overview card
   report post-cleaning numbers (e.g. "204 rows" for a Titanic upload that
   actually had 891 rows), directly contradicting the Executive Summary
   (generated by the LLM from the original profile) and the Statistical
   Summary table (built from the original profile's per-column stats) on
   the same page. Both numbers were individually correct -- 204 really is
   the row count after a "drop" missing-value strategy removed every row
   missing the highly-incomplete Cabin column -- but a banner that says
   "Upload Successful! ... 204 rows" for a file that had 891 rows is wrong
   regardless. `ctx` is now always built from `profile_original`. Only two
   things in this module still deliberately use the cleaned profile:
   `quality_source_profile` (quality reflects the data's state *after*
   cleaning, which is correct) and `before_ctx`/`before_after` (the whole
   point of that section is to show original vs. cleaned side by side).

4. ADDED (this revision) -- Bug #3 diagnostics (NOT a fix; logging only).
   A separately reported issue: after a "drop" duplicates strategy runs,
   the final cleaned_profile can still show a nonzero duplicate count,
   which is mathematically impossible for an exact-match dedup. This module
   now logs a comparison of original vs. cleaned duplicate counts and warns
   loudly when that impossible case is observed, without changing any
   duplicate-removal or cleaning logic. A complementary, finer-grained
   diagnostic (row counts immediately before/after the dedup step) was
   added in `app/tools/cleaner.py`'s `clean_csv` -- cross-reference by
   file_id to narrow down whether the problem is in `_apply_duplicates`
   itself or introduced by a later cleaning step.
"""

from typing import Any, Optional

from app.services.before_after import compute_before_after
from app.services.cleaning_report import (
    build_ai_decisions,
    build_cleaning_summary,
    build_cleaning_timeline,
)
from app.services.executive_summary import format_executive_summary
from app.services.file_service import chart_path_to_url
from app.services.insights import build_dataset_insights
from app.services.ml_presentation import (
    build_model_cards,
    build_model_readiness,
    build_why_not_others,
)
from app.services.overview import build_dataset_health, build_dataset_overview
from app.services.pipeline_context import PipelineContext
from app.services.quality_presentation import (
    build_quality_dashboard,
    build_quality_issue_cards,
)
from app.tools.data_quality import compute_quality_score
from app.utils.logger import get_logger

logger = get_logger(__name__)


def _build_chart_manifest(charts_raw: Optional[list[dict[str, Any]]]) -> list[dict[str, Any]]:
    """Convert visualizer.py's chart metadata into the frontend-facing shape.

    Each item in `charts_raw` (from `state["charts"]`, i.e.
    `visualizer.generate_charts`'s return value) already has real
    chart_type/title/description/interpretation -- this function's only job
    is rewriting `path` from an absolute filesystem path to a `/charts/...`
    URL via the shared `chart_path_to_url`. Skips malformed entries (missing
    `path`) rather than emitting a broken card, and tolerates the old bare-
    path-string shape from reports written before visualizer.py returned
    structured metadata.
    """
    if not charts_raw:
        return []
    manifest: list[dict[str, Any]] = []
    for item in charts_raw:
        if isinstance(item, dict):
            path = item.get("path")
            if not path:
                continue
            manifest.append({
                "path": chart_path_to_url(path),
                "chart_type": item.get("chart_type") or "chart",
                "title": item.get("title") or path.rsplit("/", 1)[-1],
                "description": item.get("description"),
                "interpretation": item.get("interpretation"),
            })
        elif isinstance(item, str):
            # Old shape: bare path string, no metadata at all.
            manifest.append({
                "path": chart_path_to_url(item),
                "chart_type": "chart",
                "title": item.rsplit("/", 1)[-1],
                "description": None,
                "interpretation": None,
            })
    return manifest


def build_results_response(file_id: str, data: dict[str, Any]) -> dict[str, Any]:
    """Return the enriched sections to merge into the existing `_response_payload`.

    Args:
        file_id: The file identifier (used for constructing download URLs
            and as the PipelineContext's request/file id -- no file I/O
            happens in this function itself).
        data: The report dict already loaded from disk in `get_results`
            (i.e. the same `data` passed to the existing `_response_payload`).

    Returns:
        A dict with keys `overview`, `quality`, `analysis`, `cleaning_summary`,
        `visualizations`, `ml_recommendation`, `downloads`, `metadata`, and
        `before_after` (only when `data["cleaned_profile"]` is present).
        Returns `{}` if there isn't enough data yet (e.g. `profile` missing)
        so the caller's legacy fields still work standalone.
    """
    profile_original = data.get("profile")
    if not profile_original:
        logger.warning("build_results_response: no 'profile' in report for file_id=%s; skipping enrichment", file_id)
        return {}

    profile_after = data.get("cleaned_profile")  # None for reports written before this field existed

    rec: dict[str, Any] = data.get("recommendations") or {}
    applied_plan: dict[str, Any] = data.get("cleaning_plan") or {}
    report_raw = data.get("report")  # dict (structured) or str (fallback) -- see graph.py's _run_analysis_llm
    charts_raw: list[dict[str, Any]] = data.get("charts") or []

    target_column = rec.get("target_column")
    problem_type = rec.get("problem_type")
    identifier_columns = rec.get("excluded_columns") or []

    # BUG #1 FIX: Overview/banner/dataset-dimensions/original-statistics must
    # ALWAYS describe the ORIGINAL uploaded dataset -- `ctx` below is built
    # from `profile_original`, never `profile_after`. Previously this used
    # `profile_after or profile_original` ("current_profile"), which made the
    # "Upload Successful!" banner and Dataset Overview card report the
    # POST-CLEANING row/column count (e.g. "204 rows") while the Executive
    # Summary -- generated by the LLM from the original profile, upstream of
    # any cleaning -- correctly said "891 rows". Both numbers were
    # individually correct, but showing the cleaned count under an "Upload
    # Successful" banner is simply wrong: nothing about what was uploaded has
    # 204 rows. Only `before_after` (built further down from its own
    # `before_ctx`) and `quality_result` (read from the already-computed,
    # cleaned-data-based `data["quality_score"]`, never from `ctx`) are meant
    # to reflect cleaned-data state -- see the module docstring's two
    # buckets: Overview/banner/dimensions/original-statistics -> original;
    # Before/After/Cleaning Results/Quality Improvements/Final dataset
    # metrics/ML-ready info -> cleaned.
    ctx = PipelineContext(
        request_id=file_id,
        file_id=file_id,
        original_file_path="",  # not needed post-hoc; nothing here re-reads the CSV
        profile=profile_original,
        row_count=int(profile_original.get("shape", {}).get("rows", 0)),
        column_count=int(profile_original.get("shape", {}).get("columns", 0)),
        target_column=target_column,
        problem_type=problem_type,
        target_reasoning=rec.get("detection_reasoning") or "",
        possible_targets=rec.get("possible_targets") or [],
        identifier_columns=identifier_columns,
    )
    # ctx.cleaned_profile is set for API completeness (PipelineContext exposes
    # this field and some future helper could legitimately want it), but
    # nothing called below (build_dataset_overview, build_dataset_insights)
    # actually reads ctx.cleaned_profile -- both read ctx.profile, which is
    # profile_original per the fix above.
    ctx.cleaned_profile = profile_after or profile_original

    # --- quality: reuse the already-computed score rather than recompute,
    # so this can never drift from what the graph actually produced. Only
    # fall back to computing it here if it's missing from the stored report.
    # Deliberately uses the CLEANED profile (falling back to original only if
    # cleaned isn't available yet) -- quality reflects "how good is my data
    # now, after cleaning", which is a "Quality Improvements" / "Final
    # dataset metrics" concern, not an "Overview" one. This is intentionally
    # a SEPARATE variable from `ctx.profile` above (not read from ctx at
    # all), so the Bug #1 fix above can't accidentally change quality
    # scoring by changing what `ctx` points to.
    quality_source_profile = profile_after or profile_original
    quality_result: dict[str, Any] = data.get("quality_score") or compute_quality_score(
        profile=quality_source_profile,
        target_column=target_column,
        problem_type=problem_type,
        identifier_columns=identifier_columns,
    )
    quality_score_value = quality_result.get("quality_score", 0)

    overview = build_dataset_overview(
        ctx,
        dataset_name=f"{file_id}.csv",
        quality_score=quality_score_value,
    )
    health = build_dataset_health(quality_score_value)
    quality_dashboard = build_quality_dashboard(quality_result)
    quality_issue_cards = build_quality_issue_cards(quality_result.get("issues", []))
    dataset_insights = build_dataset_insights(ctx)
    executive_summary = format_executive_summary(report_raw or "")

    cleaning_timeline = build_cleaning_timeline(applied_plan)
    ai_decisions = build_ai_decisions(cleaning_timeline)

    chart_manifest = _build_chart_manifest(charts_raw)

    result: dict[str, Any] = {
        "overview": overview,
        "quality": {
            "score": quality_score_value,
            "components": quality_result.get("components", {}),
            "dashboard": quality_dashboard,
            "health": health,
            "issues": quality_issue_cards,
        },
        "analysis": {
            "executive_summary": executive_summary,
            "dataset_insights": dataset_insights,
        },
        "visualizations": {
            "charts": chart_manifest,
        },
        "ml_recommendation": {
            "problem_type": rec.get("problem_type"),
            "target_column": rec.get("target_column"),
            "detection_reasoning": rec.get("detection_reasoning"),
            "top_recommendation": rec.get("top_recommendation"),
            "models": build_model_cards(rec.get("ranked_models") or []),
            "why_not_others": build_why_not_others(rec.get("ranked_models") or []),
            "readiness": build_model_readiness(rec),
            "warnings": rec.get("warnings") or [],
        },
        "downloads": {
            "cleaned_csv": f"/download/{file_id}" if data.get("cleaned_file") else None,
            # charts_zip is now real -- see routes.py's download_charts_zip.
            "charts_zip": f"/download/charts/{file_id}" if chart_manifest else None,
            # These two still don't have generator functions -- left null so
            # the frontend's download-center cards render as "Unavailable"
            # instead of a broken link.
            "analysis_report": None,
            # Issue 5 fix: was "/results/{file_id}" -- a real endpoint, but
            # NOT under the frontend's `safeResolveAssetUrl` allowlist
            # (/charts/, /download/ only), so it always rendered as
            # "Unavailable" despite this field having a real value. Routed
            # through the new /download/json/{file_id} endpoint instead,
            # which serves the same report data as a proper attachment
            # download rather than the inline API response.
            "json_results": f"/download/json/{file_id}",
            "cleaning_log": None,
        },
        "metadata": {
            "row_count": ctx.row_count,
            "column_count": ctx.column_count,
            # Per-stage timings aren't captured by the current graph state.
            # Wiring real numbers here requires timing each node in
            # agents/graph.py (see PipelineContext.timed() in
            # app/services/pipeline_context.py for a ready-made helper) and
            # adding the result to the stored report dict.
            "processing_metrics": {},
        },
    }

    if profile_after is not None:
        # --- Bug #3 diagnostics (DO NOT FIX HERE -- logging only) ---
        # A reported inconsistency: after a "drop" duplicates strategy runs,
        # the FINAL re-profiled cleaned_profile can still show a nonzero
        # duplicate count, which is mathematically impossible for an exact-
        # match `df.drop_duplicates()` on the same columns (by definition, no
        # row can duplicate another after dropping duplicates). This block
        # only *observes* that at the profile level -- it does not attempt to
        # fix duplicate counting, and does not change any cleaning behavior.
        #
        # This layer only has the ORIGINAL and FINAL profiles, not the
        # intermediate per-stage row counts (rows immediately after dedup vs.
        # after later steps like outlier removal/encoding) -- that finer
        # breakdown is logged separately, at the point it actually happens,
        # in app/tools/cleaner.py's `clean_csv` (see that file's own Bug #3
        # diagnostic block). Cross-reference by file_id: if cleaner.py's log
        # shows 0 duplicates immediately post-dedup but this block still
        # warns, the discrepancy is introduced AFTER dedup (outliers,
        # encoding, or the final write/re-read cycle); if cleaner.py's log
        # already shows nonzero duplicates immediately post-dedup, the issue
        # is in `_apply_duplicates`/the dedup strategy value itself.
        original_duplicates = profile_original.get("duplicates", 0)
        cleaned_duplicates = profile_after.get("duplicates", 0)
        rows_before_cleaning = profile_original.get("shape", {}).get("rows", 0)
        rows_after_cleaning = profile_after.get("shape", {}).get("rows", 0)
        dedup_action = applied_plan.get("duplicates")
        dedup_was_applied = dedup_action == "drop" or (
            isinstance(dedup_action, dict) and dedup_action.get("action") == "drop"
        )
        logger.info(
            "Bug #3 diagnostics [file_id=%s]: original_duplicates=%s cleaned_duplicates=%s "
            "rows_before_cleaning=%s rows_after_cleaning=%s total_rows_removed=%s dedup_strategy_applied=%s",
            file_id, original_duplicates, cleaned_duplicates, rows_before_cleaning, rows_after_cleaning,
            rows_before_cleaning - rows_after_cleaning, dedup_was_applied,
        )
        if dedup_was_applied and cleaned_duplicates > 0:
            logger.warning(
                "Bug #3 diagnostics [file_id=%s]: DUPLICATE COUNT MISMATCH -- a 'drop' duplicates "
                "strategy was applied, but the FINAL cleaned_profile still reports %s duplicate "
                "row(s) out of %s rows (%.1f%%). An exact-match drop_duplicates() cannot "
                "mathematically leave residual exact duplicates behind. Cross-reference this "
                "file_id's app/tools/cleaner.py diagnostic log lines (from the original /analyze "
                "call) to see whether duplicates were already present immediately after the dedup "
                "step, or were only introduced by a later step.",
                file_id, cleaned_duplicates, rows_after_cleaning,
                (cleaned_duplicates / rows_after_cleaning * 100) if rows_after_cleaning else 0.0,
            )

        # Real before/after is possible now -- build it from the TRUE
        # original/cleaned pair, using a separate context so this doesn't
        # depend on (or get confused with) `ctx` above.
        before_ctx = PipelineContext(
            request_id=file_id,
            file_id=file_id,
            original_file_path="",
            profile=profile_original,
            row_count=int(profile_original.get("shape", {}).get("rows", 0)),
            column_count=int(profile_original.get("shape", {}).get("columns", 0)),
            target_column=target_column,
            problem_type=problem_type,
            identifier_columns=identifier_columns,
        )
        before_ctx.cleaned_profile = profile_after
        try:
            before_after = compute_before_after(before_ctx, applied_plan)
            result["before_after"] = before_after
            result["cleaning_summary"] = {
                **build_cleaning_summary(applied_plan, before_after, execution_time_seconds=0.0),
                "timeline": cleaning_timeline,
                "ai_decisions": ai_decisions,
            }
        except Exception:  # noqa: BLE001 -- enrichment must never break /results
            logger.exception("Failed to compute before/after for file_id=%s despite cleaned_profile present", file_id)
            result["cleaning_summary"] = {"timeline": cleaning_timeline, "ai_decisions": ai_decisions}
    else:
        result["cleaning_summary"] = {
            "timeline": cleaning_timeline,
            "ai_decisions": ai_decisions,
            "note": (
                "rows_affected/columns_affected/before_after are unavailable "
                "for this report -- it was generated before agents/graph.py "
                "started persisting 'cleaned_profile'. Re-run /analyze on "
                "this file to get the full comparison."
            ),
        }

    return result