"""FastAPI application entrypoint."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.api.routes import router
from app.utils.config import Config
from app.utils.logger import get_logger

logger = get_logger(__name__)

app = FastAPI(title="AI Data Analyst Agent", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Chart PNGs are generated by visualizer.py and referenced by the frontend as
# /charts/<filename> -- serving them as static files avoids re-encoding image
# bytes through a JSON API response.
app.mount("/charts", StaticFiles(directory=Config.CHARTS_FOLDER), name="charts")

app.include_router(router)


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}
