"""FastAPI application entrypoint."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.api.errors import APIError, api_error_handler
from app.api.routes import router
from app.services.file_service import purge_expired_artifacts
from app.utils.config import Config
from app.utils.logger import get_logger

logger = get_logger(__name__)

app = FastAPI(title="AI Data Analyst Agent", version="0.1.0")

# Typed error envelope: any APIError raised in a route serializes to
# {"success": false, "error": {"type", "message"}, "detail": "..."} instead of
# a bare 500 (robustness spec, section 7).
app.add_exception_handler(APIError, api_error_handler)


@app.on_event("startup")
def _sweep_expired_artifacts() -> None:
    """Delete stale uploads/outputs on boot so the folders don't grow forever."""
    try:
        purge_expired_artifacts()
    except Exception:  # noqa: BLE001 -- a sweep failure must never block startup
        logger.exception("Startup artifact sweep failed; continuing without it")

app.add_middleware(
    CORSMiddleware,
    # Restricted to the origins configured in Config.CORS_ALLOW_ORIGINS (env
    # var CORS_ALLOW_ORIGINS). Never "*" -- a wildcard with allow_credentials
    # is rejected by browsers and would let any site call the API. In
    # production this must be set to the real frontend origin(s).
    allow_origins=Config.CORS_ALLOW_ORIGINS,
    allow_credentials=True,
    # Only the methods and headers the frontend actually uses. GET (results/
    # download/charts), POST (upload/analyze), and OPTIONS (CORS preflight) are
    # the full surface; Content-Type covers JSON and multipart upload requests.
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["Content-Type"],
)

# Chart PNGs are generated by visualizer.py and referenced by the frontend as
# /charts/<filename> -- serving them as static files avoids re-encoding image
# bytes through a JSON API response.
app.mount("/charts", StaticFiles(directory=Config.CHARTS_FOLDER), name="charts")

app.include_router(router)


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}
