"""FastAPI application entrypoint."""

import threading
import time
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles

from app.api.errors import APIError, api_error_handler
from app.api.routes import router
from app.services.file_service import purge_expired_artifacts
from app.utils.config import Config
from app.utils.logger import get_logger

logger = get_logger(__name__)

# How often the background sweep thread runs (seconds). Independent of
# ARTIFACT_RETENTION_HOURS -- that controls *age* of files to delete; this
# controls *frequency* of checks. Run every 5 minutes to stay within the
# short 15-min TTL window (a 1-hour interval with a 15-min TTL would allow
# files to linger up to ~75 minutes worst-case).
_CLEANUP_INTERVAL_SECONDS = 300


def _background_cleanup_loop() -> None:
    """Run purge_expired_artifacts() on a fixed interval in a daemon thread.

    On-startup-only cleanup (the old @on_event approach) means a long-running
    server process that isn't restarted will accumulate uploads and outputs
    until disk fills. This thread ensures cleanup happens periodically even
    between restarts.
    """
    while True:
        time.sleep(_CLEANUP_INTERVAL_SECONDS)
        try:
            purge_expired_artifacts()
        except Exception:  # noqa: BLE001 -- never crash the cleanup thread
            logger.exception("Periodic artifact sweep failed; will retry next interval")


@asynccontextmanager
async def lifespan(_app: FastAPI):
    """Startup/shutdown lifecycle (replaces deprecated @app.on_event)."""
    # --- startup ---
    try:
        purge_expired_artifacts()
    except Exception:  # noqa: BLE001 -- sweep failure must never block startup
        logger.exception("Startup artifact sweep failed; continuing without it")

    # Launch the periodic cleanup daemon thread (FIX 8: runs every hour,
    # not only at startup, so disk doesn't fill between restarts).
    _cleanup_thread = threading.Thread(
        target=_background_cleanup_loop,
        name="artifact-cleanup",
        daemon=True,  # daemon=True: thread exits when the main process exits
    )
    _cleanup_thread.start()
    logger.info("Periodic artifact cleanup thread started (interval=%ds)", _CLEANUP_INTERVAL_SECONDS)

    yield  # app is running

    # --- shutdown (nothing extra needed; daemon thread exits automatically) ---


app = FastAPI(title="AI Data Analyst Agent", version="0.1.0", lifespan=lifespan)

# Typed error envelope: any APIError raised in a route serializes to
# {"success": false, "error": {"type", "message"}, "detail": "..."} instead of
# a bare 500 (robustness spec, section 7).
app.add_exception_handler(APIError, api_error_handler)


# FIX 6: Catch-all handler for any unhandled exception.
# Without this, FastAPI returns its default {"detail": "Internal Server Error"}
# with a raw traceback sometimes leaking into debug output. This guarantees
# a clean JSON envelope and logs the full traceback server-side.
@app.exception_handler(Exception)
async def _unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    logger.exception(
        "Unhandled exception on %s %s", request.method, request.url.path
    )
    return JSONResponse(
        status_code=500,
        content={
            "success": False,
            "error": {"type": "INTERNAL_ERROR", "message": "An unexpected internal error occurred."},
            "detail": "An unexpected internal error occurred.",
        },
    )


app.add_middleware(
    CORSMiddleware,
    # Restricted to the origins configured in Config.CORS_ALLOW_ORIGINS (env
    # var CORS_ALLOW_ORIGINS). Never "*" -- a wildcard with allow_credentials
    # is rejected by browsers and would let any site call the API. In
    # production this must be set to the real frontend origin(s).
    allow_origins=Config.CORS_ALLOW_ORIGINS,
    allow_credentials=True,
    # Only the methods and headers the frontend actually uses. GET (results/
    # download/charts), POST (upload/analyze), and OPTIONS (CORS preflight) are
    # the full surface; Content-Type covers JSON and multipart upload requests.
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["Content-Type"],
)

# Chart PNGs are generated by visualizer.py and referenced by the frontend as
# /charts/<filename> -- serving them as static files avoids re-encoding image
# bytes through a JSON API response.
app.mount("/charts", StaticFiles(directory=Config.CHARTS_FOLDER), name="charts")

app.include_router(router)


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}
